#!/bin/bash

help() {
  echo "Usage:"
  echo "  zmicro package install davfs <args...>"
  echo ""
}

core() {
  if [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    help
    exit 0
  fi

  which mount.davfs >>/dev/null 2>&1
  if [ "$?" != "0" ]; then
    pm install -y davfs2
  fi

  log::success "install davfs (davfs2) success."
}

run() {
  core $@
}

run $@
